version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - chore
      - dependencies
      - auto_pr
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]