name: Android CI

on:
  pull_request:
    branches: [ develop, "feature*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Ruby 2.6.10
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
      - name: Install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.36.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/
      - name: Run Unit Test
        run: |
          bundle exec fastlane unit_test
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKENCI }}
